// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: keye.proto

package keye

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_EVENT_KEEPALIVE Event = 0
	Event_EVENT_ADDED     Event = 1
	Event_EVENT_MODIFIED  Event = 2
	Event_EVENT_DELETED   Event = 3
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "EVENT_KEEPALIVE",
		1: "EVENT_ADDED",
		2: "EVENT_MODIFIED",
		3: "EVENT_DELETED",
	}
	Event_value = map[string]int32{
		"EVENT_KEEPALIVE": 0,
		"EVENT_ADDED":     1,
		"EVENT_MODIFIED":  2,
		"EVENT_DELETED":   3,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_keye_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_keye_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{0}
}

type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type GetParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Opts *GetOpts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *GetParams) Reset() {
	*x = GetParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParams) ProtoMessage() {}

func (x *GetParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParams.ProtoReflect.Descriptor instead.
func (*GetParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{1}
}

func (x *GetParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetParams) GetOpts() *GetOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type GetOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithPrefix   *bool `protobuf:"varint,1,opt,name=with_prefix,json=withPrefix,proto3,oneof" json:"with_prefix,omitempty"`
	WithRegex    *bool `protobuf:"varint,2,opt,name=with_regex,json=withRegex,proto3,oneof" json:"with_regex,omitempty"`
	WithKeysOnly *bool `protobuf:"varint,3,opt,name=with_keys_only,json=withKeysOnly,proto3,oneof" json:"with_keys_only,omitempty"`
}

func (x *GetOpts) Reset() {
	*x = GetOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpts) ProtoMessage() {}

func (x *GetOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpts.ProtoReflect.Descriptor instead.
func (*GetOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{2}
}

func (x *GetOpts) GetWithPrefix() bool {
	if x != nil && x.WithPrefix != nil {
		return *x.WithPrefix
	}
	return false
}

func (x *GetOpts) GetWithRegex() bool {
	if x != nil && x.WithRegex != nil {
		return *x.WithRegex
	}
	return false
}

func (x *GetOpts) GetWithKeysOnly() bool {
	if x != nil && x.WithKeysOnly != nil {
		return *x.WithKeysOnly
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kvs []*KV `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetKvs() []*KV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type PutParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Opts *PutOpts `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *PutParams) Reset() {
	*x = PutParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutParams) ProtoMessage() {}

func (x *PutParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutParams.ProtoReflect.Descriptor instead.
func (*PutParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{4}
}

func (x *PutParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutParams) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *PutParams) GetOpts() *PutOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type PutOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithPrefix *bool `protobuf:"varint,1,opt,name=with_prefix,json=withPrefix,proto3,oneof" json:"with_prefix,omitempty"`
	WithRegex  *bool `protobuf:"varint,2,opt,name=with_regex,json=withRegex,proto3,oneof" json:"with_regex,omitempty"`
}

func (x *PutOpts) Reset() {
	*x = PutOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOpts) ProtoMessage() {}

func (x *PutOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOpts.ProtoReflect.Descriptor instead.
func (*PutOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{5}
}

func (x *PutOpts) GetWithPrefix() bool {
	if x != nil && x.WithPrefix != nil {
		return *x.WithPrefix
	}
	return false
}

func (x *PutOpts) GetWithRegex() bool {
	if x != nil && x.WithRegex != nil {
		return *x.WithRegex
	}
	return false
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{6}
}

func (x *PutResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DelParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Opts *DelOpts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *DelParams) Reset() {
	*x = DelParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelParams) ProtoMessage() {}

func (x *DelParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelParams.ProtoReflect.Descriptor instead.
func (*DelParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{7}
}

func (x *DelParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DelParams) GetOpts() *DelOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type DelOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithPrefix *bool `protobuf:"varint,1,opt,name=with_prefix,json=withPrefix,proto3,oneof" json:"with_prefix,omitempty"`
	WithRegex  *bool `protobuf:"varint,2,opt,name=with_regex,json=withRegex,proto3,oneof" json:"with_regex,omitempty"`
}

func (x *DelOpts) Reset() {
	*x = DelOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOpts) ProtoMessage() {}

func (x *DelOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOpts.ProtoReflect.Descriptor instead.
func (*DelOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{8}
}

func (x *DelOpts) GetWithPrefix() bool {
	if x != nil && x.WithPrefix != nil {
		return *x.WithPrefix
	}
	return false
}

func (x *DelOpts) GetWithRegex() bool {
	if x != nil && x.WithRegex != nil {
		return *x.WithRegex
	}
	return false
}

type DelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{9}
}

func (x *DelResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type WatchParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Opts *WatchOpts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *WatchParams) Reset() {
	*x = WatchParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchParams) ProtoMessage() {}

func (x *WatchParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchParams.ProtoReflect.Descriptor instead.
func (*WatchParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{10}
}

func (x *WatchParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchParams) GetOpts() *WatchOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type WatchOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithPrefix *bool `protobuf:"varint,1,opt,name=with_prefix,json=withPrefix,proto3,oneof" json:"with_prefix,omitempty"`
	WithRegex  *bool `protobuf:"varint,2,opt,name=with_regex,json=withRegex,proto3,oneof" json:"with_regex,omitempty"`
}

func (x *WatchOpts) Reset() {
	*x = WatchOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchOpts) ProtoMessage() {}

func (x *WatchOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchOpts.ProtoReflect.Descriptor instead.
func (*WatchOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{11}
}

func (x *WatchOpts) GetWithPrefix() bool {
	if x != nil && x.WithPrefix != nil {
		return *x.WithPrefix
	}
	return false
}

func (x *WatchOpts) GetWithRegex() bool {
	if x != nil && x.WithRegex != nil {
		return *x.WithRegex
	}
	return false
}

type WatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event Event `protobuf:"varint,1,opt,name=event,proto3,enum=keye.Event" json:"event,omitempty"`
	Kvs   []*KV `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{12}
}

func (x *WatchResponse) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_EVENT_KEEPALIVE
}

func (x *WatchResponse) GetKvs() []*KV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

var File_keye_proto protoreflect.FileDescriptor

var file_keye_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x65,
	0x79, 0x65, 0x22, 0x28, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x40, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x6f,
	0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x65, 0x79, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0xb0,
	0x01, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x77, 0x69,
	0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01,
	0x12, 0x22, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x09, 0x77, 0x69, 0x74, 0x68, 0x52, 0x65, 0x67, 0x65,
	0x78, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79,
	0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x0c,
	0x77, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42,
	0x0d, 0x0a, 0x0b, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x42, 0x11,
	0x0a, 0x0f, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x6f, 0x6e, 0x6c,
	0x79, 0x22, 0x29, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x6b, 0x65, 0x79, 0x65, 0x2e, 0x4b, 0x56, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22, 0x52, 0x0a, 0x09,
	0x50, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x21, 0x0a,
	0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x65,
	0x79, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73,
	0x22, 0x72, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x77,
	0x69, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01,
	0x01, 0x12, 0x22, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x09, 0x77, 0x69, 0x74, 0x68, 0x52, 0x65, 0x67,
	0x65, 0x78, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x72,
	0x65, 0x67, 0x65, 0x78, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x40, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x4f,
	0x70, 0x74, 0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x72, 0x0a, 0x07, 0x44, 0x65, 0x6c,
	0x4f, 0x70, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0a, 0x77, 0x69, 0x74,
	0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x77, 0x69,
	0x74, 0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01,
	0x52, 0x09, 0x77, 0x69, 0x74, 0x68, 0x52, 0x65, 0x67, 0x65, 0x78, 0x88, 0x01, 0x01, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x22, 0x21, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x22, 0x44, 0x0a, 0x0b, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x23, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x73,
	0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x74, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4f,
	0x70, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68,
	0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52,
	0x09, 0x77, 0x69, 0x74, 0x68, 0x52, 0x65, 0x67, 0x65, 0x78, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a,
	0x0c, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x22, 0x4e, 0x0a, 0x0d,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6b,
	0x65, 0x79, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x6b, 0x65, 0x79, 0x65, 0x2e, 0x4b, 0x56, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x2a, 0x54, 0x0a, 0x05,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x4b,
	0x45, 0x45, 0x50, 0x41, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45,
	0x56, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x11, 0x0a, 0x0d, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44,
	0x10, 0x03, 0x32, 0xb9, 0x01, 0x0a, 0x03, 0x41, 0x70, 0x69, 0x12, 0x29, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x0f, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x0f, 0x2e, 0x6b,
	0x65, 0x79, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e,
	0x6b, 0x65, 0x79, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0f, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e,
	0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x13, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x1b,
	0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x72,
	0x74, 0x61, 0x7a, 0x61, 0x2d, 0x75, 0x2f, 0x6b, 0x65, 0x79, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_keye_proto_rawDescOnce sync.Once
	file_keye_proto_rawDescData = file_keye_proto_rawDesc
)

func file_keye_proto_rawDescGZIP() []byte {
	file_keye_proto_rawDescOnce.Do(func() {
		file_keye_proto_rawDescData = protoimpl.X.CompressGZIP(file_keye_proto_rawDescData)
	})
	return file_keye_proto_rawDescData
}

var file_keye_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keye_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_keye_proto_goTypes = []interface{}{
	(Event)(0),            // 0: keye.Event
	(*KV)(nil),            // 1: keye.KV
	(*GetParams)(nil),     // 2: keye.GetParams
	(*GetOpts)(nil),       // 3: keye.GetOpts
	(*GetResponse)(nil),   // 4: keye.GetResponse
	(*PutParams)(nil),     // 5: keye.PutParams
	(*PutOpts)(nil),       // 6: keye.PutOpts
	(*PutResponse)(nil),   // 7: keye.PutResponse
	(*DelParams)(nil),     // 8: keye.DelParams
	(*DelOpts)(nil),       // 9: keye.DelOpts
	(*DelResponse)(nil),   // 10: keye.DelResponse
	(*WatchParams)(nil),   // 11: keye.WatchParams
	(*WatchOpts)(nil),     // 12: keye.WatchOpts
	(*WatchResponse)(nil), // 13: keye.WatchResponse
}
var file_keye_proto_depIdxs = []int32{
	3,  // 0: keye.GetParams.opts:type_name -> keye.GetOpts
	1,  // 1: keye.GetResponse.kvs:type_name -> keye.KV
	6,  // 2: keye.PutParams.opts:type_name -> keye.PutOpts
	9,  // 3: keye.DelParams.opts:type_name -> keye.DelOpts
	12, // 4: keye.WatchParams.opts:type_name -> keye.WatchOpts
	0,  // 5: keye.WatchResponse.event:type_name -> keye.Event
	1,  // 6: keye.WatchResponse.kvs:type_name -> keye.KV
	2,  // 7: keye.Api.Get:input_type -> keye.GetParams
	5,  // 8: keye.Api.Put:input_type -> keye.PutParams
	8,  // 9: keye.Api.Del:input_type -> keye.DelParams
	11, // 10: keye.Api.Watch:input_type -> keye.WatchParams
	4,  // 11: keye.Api.Get:output_type -> keye.GetResponse
	7,  // 12: keye.Api.Put:output_type -> keye.PutResponse
	10, // 13: keye.Api.Del:output_type -> keye.DelResponse
	13, // 14: keye.Api.Watch:output_type -> keye.WatchResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_keye_proto_init() }
func file_keye_proto_init() {
	if File_keye_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keye_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keye_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_keye_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_keye_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_keye_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keye_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keye_proto_goTypes,
		DependencyIndexes: file_keye_proto_depIdxs,
		EnumInfos:         file_keye_proto_enumTypes,
		MessageInfos:      file_keye_proto_msgTypes,
	}.Build()
	File_keye_proto = out.File
	file_keye_proto_rawDesc = nil
	file_keye_proto_goTypes = nil
	file_keye_proto_depIdxs = nil
}
