// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: keye.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_EVENT_KEEPALIVE Event = 0
	Event_EVENT_PUT       Event = 1
	Event_EVENT_DEL       Event = 2
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "EVENT_KEEPALIVE",
		1: "EVENT_PUT",
		2: "EVENT_DEL",
	}
	Event_value = map[string]int32{
		"EVENT_KEEPALIVE": 0,
		"EVENT_PUT":       1,
		"EVENT_DEL":       2,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_keye_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_keye_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{0}
}

type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type GetParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Opts *GetOpts `protobuf:"bytes,2,opt,name=opts,proto3,oneof" json:"opts,omitempty"`
}

func (x *GetParams) Reset() {
	*x = GetParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParams) ProtoMessage() {}

func (x *GetParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParams.ProtoReflect.Descriptor instead.
func (*GetParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{1}
}

func (x *GetParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetParams) GetOpts() *GetOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type GetOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regex    bool `protobuf:"varint,1,opt,name=regex,proto3" json:"regex,omitempty"`
	KeysOnly bool `protobuf:"varint,2,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
}

func (x *GetOpts) Reset() {
	*x = GetOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpts) ProtoMessage() {}

func (x *GetOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpts.ProtoReflect.Descriptor instead.
func (*GetOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{2}
}

func (x *GetOpts) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

func (x *GetOpts) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kvs []*KV `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetKvs() []*KV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type PutParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Opts *PutOpts `protobuf:"bytes,3,opt,name=opts,proto3,oneof" json:"opts,omitempty"`
}

func (x *PutParams) Reset() {
	*x = PutParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutParams) ProtoMessage() {}

func (x *PutParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutParams.ProtoReflect.Descriptor instead.
func (*PutParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{4}
}

func (x *PutParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutParams) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *PutParams) GetOpts() *PutOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type PutOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regex bool `protobuf:"varint,1,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *PutOpts) Reset() {
	*x = PutOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOpts) ProtoMessage() {}

func (x *PutOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOpts.ProtoReflect.Descriptor instead.
func (*PutOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{5}
}

func (x *PutOpts) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{6}
}

func (x *PutResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DelParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Opts *DelOpts `protobuf:"bytes,2,opt,name=opts,proto3,oneof" json:"opts,omitempty"`
}

func (x *DelParams) Reset() {
	*x = DelParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelParams) ProtoMessage() {}

func (x *DelParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelParams.ProtoReflect.Descriptor instead.
func (*DelParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{7}
}

func (x *DelParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DelParams) GetOpts() *DelOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type DelOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regex bool `protobuf:"varint,1,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *DelOpts) Reset() {
	*x = DelOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOpts) ProtoMessage() {}

func (x *DelOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOpts.ProtoReflect.Descriptor instead.
func (*DelOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{8}
}

func (x *DelOpts) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

type DelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{9}
}

func (x *DelResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type WatchParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Opts *WatchOpts `protobuf:"bytes,2,opt,name=opts,proto3,oneof" json:"opts,omitempty"`
}

func (x *WatchParams) Reset() {
	*x = WatchParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchParams) ProtoMessage() {}

func (x *WatchParams) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchParams.ProtoReflect.Descriptor instead.
func (*WatchParams) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{10}
}

func (x *WatchParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchParams) GetOpts() *WatchOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type WatchOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regex bool `protobuf:"varint,1,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *WatchOpts) Reset() {
	*x = WatchOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchOpts) ProtoMessage() {}

func (x *WatchOpts) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchOpts.ProtoReflect.Descriptor instead.
func (*WatchOpts) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{11}
}

func (x *WatchOpts) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

type WatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event Event `protobuf:"varint,1,opt,name=event,proto3,enum=pb.Event" json:"event,omitempty"`
	Kv    *KV   `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{12}
}

func (x *WatchResponse) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_EVENT_KEEPALIVE
}

func (x *WatchResponse) GetKv() *KV {
	if x != nil {
		return x.Kv
	}
	return nil
}

type Delta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration int64 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *Delta) Reset() {
	*x = Delta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{13}
}

func (x *Delta) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Measures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxStats       *TxStats `protobuf:"bytes,1,opt,name=TxStats,proto3" json:"TxStats,omitempty"`
	FreePageN     int32    `protobuf:"varint,2,opt,name=FreePageN,proto3" json:"FreePageN,omitempty"`
	PendingPageN  int32    `protobuf:"varint,3,opt,name=PendingPageN,proto3" json:"PendingPageN,omitempty"`
	FreeAlloc     int32    `protobuf:"varint,4,opt,name=FreeAlloc,proto3" json:"FreeAlloc,omitempty"`
	FreelistInuse int32    `protobuf:"varint,5,opt,name=FreelistInuse,proto3" json:"FreelistInuse,omitempty"`
	TxN           int32    `protobuf:"varint,6,opt,name=TxN,proto3" json:"TxN,omitempty"`
	OpenTxN       int32    `protobuf:"varint,7,opt,name=OpenTxN,proto3" json:"OpenTxN,omitempty"`
}

func (x *Measures) Reset() {
	*x = Measures{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measures) ProtoMessage() {}

func (x *Measures) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measures.ProtoReflect.Descriptor instead.
func (*Measures) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{14}
}

func (x *Measures) GetTxStats() *TxStats {
	if x != nil {
		return x.TxStats
	}
	return nil
}

func (x *Measures) GetFreePageN() int32 {
	if x != nil {
		return x.FreePageN
	}
	return 0
}

func (x *Measures) GetPendingPageN() int32 {
	if x != nil {
		return x.PendingPageN
	}
	return 0
}

func (x *Measures) GetFreeAlloc() int32 {
	if x != nil {
		return x.FreeAlloc
	}
	return 0
}

func (x *Measures) GetFreelistInuse() int32 {
	if x != nil {
		return x.FreelistInuse
	}
	return 0
}

func (x *Measures) GetTxN() int32 {
	if x != nil {
		return x.TxN
	}
	return 0
}

func (x *Measures) GetOpenTxN() int32 {
	if x != nil {
		return x.OpenTxN
	}
	return 0
}

type TxStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageCount     int64 `protobuf:"varint,1,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	PageAlloc     int64 `protobuf:"varint,2,opt,name=PageAlloc,proto3" json:"PageAlloc,omitempty"`
	CursorCount   int64 `protobuf:"varint,3,opt,name=CursorCount,proto3" json:"CursorCount,omitempty"`
	NodeCount     int64 `protobuf:"varint,4,opt,name=NodeCount,proto3" json:"NodeCount,omitempty"`
	NodeDeref     int64 `protobuf:"varint,5,opt,name=NodeDeref,proto3" json:"NodeDeref,omitempty"`
	Rebalance     int64 `protobuf:"varint,6,opt,name=Rebalance,proto3" json:"Rebalance,omitempty"`
	RebalanceTime int64 `protobuf:"varint,7,opt,name=RebalanceTime,proto3" json:"RebalanceTime,omitempty"`
	Split         int64 `protobuf:"varint,8,opt,name=Split,proto3" json:"Split,omitempty"`
	Spill         int64 `protobuf:"varint,9,opt,name=Spill,proto3" json:"Spill,omitempty"`
	SpillTime     int64 `protobuf:"varint,10,opt,name=SpillTime,proto3" json:"SpillTime,omitempty"`
	Write         int64 `protobuf:"varint,11,opt,name=Write,proto3" json:"Write,omitempty"`
	WriteTime     int64 `protobuf:"varint,12,opt,name=WriteTime,proto3" json:"WriteTime,omitempty"`
}

func (x *TxStats) Reset() {
	*x = TxStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStats) ProtoMessage() {}

func (x *TxStats) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStats.ProtoReflect.Descriptor instead.
func (*TxStats) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{15}
}

func (x *TxStats) GetPageCount() int64 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *TxStats) GetPageAlloc() int64 {
	if x != nil {
		return x.PageAlloc
	}
	return 0
}

func (x *TxStats) GetCursorCount() int64 {
	if x != nil {
		return x.CursorCount
	}
	return 0
}

func (x *TxStats) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *TxStats) GetNodeDeref() int64 {
	if x != nil {
		return x.NodeDeref
	}
	return 0
}

func (x *TxStats) GetRebalance() int64 {
	if x != nil {
		return x.Rebalance
	}
	return 0
}

func (x *TxStats) GetRebalanceTime() int64 {
	if x != nil {
		return x.RebalanceTime
	}
	return 0
}

func (x *TxStats) GetSplit() int64 {
	if x != nil {
		return x.Split
	}
	return 0
}

func (x *TxStats) GetSpill() int64 {
	if x != nil {
		return x.Spill
	}
	return 0
}

func (x *TxStats) GetSpillTime() int64 {
	if x != nil {
		return x.SpillTime
	}
	return 0
}

func (x *TxStats) GetWrite() int64 {
	if x != nil {
		return x.Write
	}
	return 0
}

func (x *TxStats) GetWriteTime() int64 {
	if x != nil {
		return x.WriteTime
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	More bool   `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{16}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

type ChunkSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ChunkSize) Reset() {
	*x = ChunkSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keye_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSize) ProtoMessage() {}

func (x *ChunkSize) ProtoReflect() protoreflect.Message {
	mi := &file_keye_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSize.ProtoReflect.Descriptor instead.
func (*ChunkSize) Descriptor() ([]byte, []int) {
	return file_keye_proto_rawDescGZIP(), []int{17}
}

func (x *ChunkSize) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_keye_proto protoreflect.FileDescriptor

var file_keye_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x28, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x6f, 0x70, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x70, 0x74, 0x73, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4f,
	0x70, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79,
	0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6b, 0x65,
	0x79, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x27, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x56, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22,
	0x5e, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x12, 0x24, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x48, 0x00, 0x52, 0x04, 0x6f,
	0x70, 0x74, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x22,
	0x1f, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65,
	0x67, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78,
	0x22, 0x21, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x22, 0x4c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x4f, 0x70, 0x74, 0x73, 0x48, 0x00, 0x52,
	0x04, 0x6f, 0x70, 0x74, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6f, 0x70, 0x74,
	0x73, 0x22, 0x1f, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x67,
	0x65, 0x78, 0x22, 0x21, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x50, 0x0a, 0x0b, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4f,
	0x70, 0x74, 0x73, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x21, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x4f, 0x70, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x22, 0x48, 0x0a, 0x0d, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x02,
	0x6b, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x56,
	0x52, 0x02, 0x6b, 0x76, 0x22, 0x23, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe3, 0x01, 0x0a, 0x08, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x07, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x46, 0x72, 0x65, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x46, 0x72, 0x65, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x12, 0x22, 0x0a, 0x0c, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x12,
	0x1c, 0x0a, 0x09, 0x46, 0x72, 0x65, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x46, 0x72, 0x65, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x12, 0x24, 0x0a,
	0x0d, 0x46, 0x72, 0x65, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x75, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x46, 0x72, 0x65, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x75, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x78, 0x4e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x54, 0x78, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x78, 0x4e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x78, 0x4e, 0x22,
	0xe5, 0x02, 0x0a, 0x07, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x67,
	0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x61,
	0x67, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x64,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4e, 0x6f,
	0x64, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x44,
	0x65, 0x72, 0x65, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65,
	0x44, 0x65, 0x72, 0x65, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x52, 0x65, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x52, 0x65, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x70, 0x69, 0x6c, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x53, 0x70, 0x69, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x70, 0x69, 0x6c, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x70, 0x69, 0x6c, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x6d, 0x6f, 0x72, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x2a, 0x3a, 0x0a, 0x05, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x4b, 0x45, 0x45, 0x50,
	0x41, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x50, 0x55, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f,
	0x44, 0x45, 0x4c, 0x10, 0x02, 0x32, 0xf1, 0x01, 0x0a, 0x03, 0x41, 0x70, 0x69, 0x12, 0x25, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x44,
	0x65, 0x6c, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x20, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x74, 0x61, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x1a, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x72, 0x74, 0x61, 0x7a, 0x61, 0x2d,
	0x75, 0x2f, 0x6b, 0x65, 0x79, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keye_proto_rawDescOnce sync.Once
	file_keye_proto_rawDescData = file_keye_proto_rawDesc
)

func file_keye_proto_rawDescGZIP() []byte {
	file_keye_proto_rawDescOnce.Do(func() {
		file_keye_proto_rawDescData = protoimpl.X.CompressGZIP(file_keye_proto_rawDescData)
	})
	return file_keye_proto_rawDescData
}

var file_keye_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keye_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_keye_proto_goTypes = []interface{}{
	(Event)(0),            // 0: pb.Event
	(*KV)(nil),            // 1: pb.KV
	(*GetParams)(nil),     // 2: pb.GetParams
	(*GetOpts)(nil),       // 3: pb.GetOpts
	(*GetResponse)(nil),   // 4: pb.GetResponse
	(*PutParams)(nil),     // 5: pb.PutParams
	(*PutOpts)(nil),       // 6: pb.PutOpts
	(*PutResponse)(nil),   // 7: pb.PutResponse
	(*DelParams)(nil),     // 8: pb.DelParams
	(*DelOpts)(nil),       // 9: pb.DelOpts
	(*DelResponse)(nil),   // 10: pb.DelResponse
	(*WatchParams)(nil),   // 11: pb.WatchParams
	(*WatchOpts)(nil),     // 12: pb.WatchOpts
	(*WatchResponse)(nil), // 13: pb.WatchResponse
	(*Delta)(nil),         // 14: pb.Delta
	(*Measures)(nil),      // 15: pb.Measures
	(*TxStats)(nil),       // 16: pb.TxStats
	(*Chunk)(nil),         // 17: pb.Chunk
	(*ChunkSize)(nil),     // 18: pb.ChunkSize
}
var file_keye_proto_depIdxs = []int32{
	3,  // 0: pb.GetParams.opts:type_name -> pb.GetOpts
	1,  // 1: pb.GetResponse.kvs:type_name -> pb.KV
	6,  // 2: pb.PutParams.opts:type_name -> pb.PutOpts
	9,  // 3: pb.DelParams.opts:type_name -> pb.DelOpts
	12, // 4: pb.WatchParams.opts:type_name -> pb.WatchOpts
	0,  // 5: pb.WatchResponse.event:type_name -> pb.Event
	1,  // 6: pb.WatchResponse.kv:type_name -> pb.KV
	16, // 7: pb.Measures.TxStats:type_name -> pb.TxStats
	2,  // 8: pb.Api.Get:input_type -> pb.GetParams
	5,  // 9: pb.Api.Put:input_type -> pb.PutParams
	8,  // 10: pb.Api.Del:input_type -> pb.DelParams
	11, // 11: pb.Api.Watch:input_type -> pb.WatchParams
	14, // 12: pb.Api.Stats:input_type -> pb.Delta
	18, // 13: pb.Api.Backup:input_type -> pb.ChunkSize
	4,  // 14: pb.Api.Get:output_type -> pb.GetResponse
	7,  // 15: pb.Api.Put:output_type -> pb.PutResponse
	10, // 16: pb.Api.Del:output_type -> pb.DelResponse
	13, // 17: pb.Api.Watch:output_type -> pb.WatchResponse
	15, // 18: pb.Api.Stats:output_type -> pb.Measures
	17, // 19: pb.Api.Backup:output_type -> pb.Chunk
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_keye_proto_init() }
func file_keye_proto_init() {
	if File_keye_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keye_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measures); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keye_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keye_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_keye_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_keye_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_keye_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keye_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keye_proto_goTypes,
		DependencyIndexes: file_keye_proto_depIdxs,
		EnumInfos:         file_keye_proto_enumTypes,
		MessageInfos:      file_keye_proto_msgTypes,
	}.Build()
	File_keye_proto = out.File
	file_keye_proto_rawDesc = nil
	file_keye_proto_goTypes = nil
	file_keye_proto_depIdxs = nil
}
